### ISSUE TITLE
Having trouble switching cameras

### ISSUE THREAD

**Issue by ryandailey100** [Awalz/SwiftyCam#1] opened 2016-12-31 04:57 UTC
I cant seem to get the cameras to switch properly. When i switch the camera, i just get a black screen and everything becomes unresponsive. Any way to fix this?

**Comment by ryandailey100** [comment] 2016-12-31 05:01
I also get this in the print log: "[SwiftyCam]: Could not add video device input to the session"

**Comment by Awalz** [comment] 2016-12-31 05:03
Can you provide me with your device info? Model info and iOS version?

Andrew

On Fri, Dec 30, 2016 at 10:01 PM Ryan Dailey

<
mailto:Ryan Dailey <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

I also get this in the print log: "[SwiftyCam]: Could not add video device input to the session"

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/Awalz/SwiftyCam/issues/1#issuecomment-269849680
, or

**Comment by ryandailey100** [comment] 2016-12-31 05:05
Im debugging on my iPhone 6 which is running iOS 9.0.2

**Comment by ryandailey100** [comment] 2017-01-01 20:31
Any update for this problem? Its got me stuck for a few days now

**Comment by Awalz** [comment] 2017-01-01 20:46
I've been away from my computer for the last three days. Will check it out when I get home (hopefully in an hour)

**Comment by ryandailey100** [comment] 2017-01-01 20:47
Okay thanks! 👍

**Comment by Awalz** [comment] 2017-01-02 03:39
I have been unable to reproduce this issue on my device (iPhone 7 running 10.2). Are you trying this on your own project or does it have the same behaviour on the example project?

I have submitted a new version 1.0.1 with some minor changes. Give it a try

**Comment by ryandailey100** [comment] 2017-01-02 03:51
I have tried this in both my project and the demo project and it still does the same thing. I also just tried with your new 1.0.1 version and still no luck. Im not sure if it has to do with me running iOS 9 and not iOS 10. Have you tested this out in iOS 9 before?

**Comment by Awalz** [comment] 2017-01-02 04:03
Can you get a count of the session input array when this issue occurs? Add 
`print( self.session.inputs.count)
`
on line 325 of SwiftyCamViewController.

**Comment by ryandailey100** [comment] 2017-01-02 04:23
I am getting 0 as the number

**Comment by Awalz** [comment] 2017-01-02 19:46
That is very strange. I am looking into this today. I need to get a hold of more test devices as mine do not reproduce this issue. Can you describe, in detail, how you are able to reproduce and what occurs in the demo app?

**Comment by ryandailey100** [comment] 2017-01-02 20:49
To reproduce this, all I did was start up the example app (with no modifications) and when the app starts up, I tap on the switch camera button. Once I tap on that button, thats when the problem occurs. 

Here is what it looks like after I tap on the switch camera button:

![img_8032](https://cloud.githubusercontent.com/assets/15038444/21596020/030300d8-d103-11e6-8cbb-58f6d73a0135.PNG)

**Comment by Awalz** [comment] 2017-01-03 01:40
Hey Ryan, I have discovered the issue.

The default implementation uses AVCaptureSessionPreset1920x1080. My iPhone 7 supports 1080p recording via the front facing camera, but yours does not. It fails to add the front facing camera when you switch cameras. It will fail on any device that does not support 1080 resolution. A temporary workaround would be to drop the videoQuality:

`           videoQuality = .resolution1280x720
`

I will issue a fix for the default implementation soon

Andrew

**Comment by Awalz** [comment] 2017-01-03 02:38
I have just pushed a new version (1.1.0). It includes a fix I believe will solve this. The default videoQaulity preset has been changed to **.high**. As well, switching to the front facing camera will always default to **.high**, even if another preset is selected. I believe this is a good compromise. If you could test and confirm it works, I will close this issue.


Andrew

**Comment by ryandailey100** [comment] 2017-01-03 03:46
Just tried it now, everything works 100% now! Thank you so much for fixing this problem. This is a bit off topic but the switchCamera() and toggleFlash() function in the SwiftyCamViewController class should both be open functions. This is because when this is installed through cocoapods, those two functions become inaccessible. I had to manually add them to get them working (since 1.0.0). Besides that, everything is all great! Thanks again for the amazing work 👍

**Comment by Awalz** [comment] 2017-01-03 05:46
Good to hear! Nice call on the wrong access control for those functions. Was an oversight on my part. I changed them all to be public accessible on 1.1.1 if you wanna check it out.

Andrew

**Closed by Awalz** 2017-01-03 05:46 UTC

**Comment by Annyjain29** [comment] 2022-12-07 10:47
I am facing same issue again , even thought i place video quality as you said
