### ISSUE TITLE
Please support switching cameras while recording

### ISSUE THREAD

**Issue by SebastainMisas** [Awalz/SwiftyCam#186] opened 2018-10-03 07:46 UTC
As of now your not able to switch the camera while recording, this is an issue I'm sure majority of developers using this library would love to have implemented. 
It would be greatly appreciated!

**Comment by Yonodactyl** [comment] 2018-10-21 02:32
If this is still available, I would like to take a crack at switch off recording!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jonandersen** [comment] 2018-11-21 16:18
Closing as it's a duplicate of #44 @Yonodactyl let me know if you did any progress on it!

**Closed by jonandersen** 2018-11-21 16:18 UTC
