### ISSUE TITLE
Bluetooth earbuds cause music to play through speakers when opening swiftycam

### ISSUE THREAD

**Issue by waterdrake** [Awalz/SwiftyCam#123] opened 2017-10-11 00:53 UTC
If you are listening to music on your phone with bluetooth earbuds and you open a swiftycam app, the music will play through the phone's speaker out loud. 

Not sure if this is fixable...?

**Comment by jonandersen** [comment] 2017-10-18 17:58
Closing as duplicate of https://github.com/Awalz/SwiftyCam/issues/78

**Closed by jonandersen** 2017-10-18 17:58 UTC
Labels: duplicate
